### PR TITLE
Decouple severity from Nagios plugin return codes

### PR DESCRIPTION
**Pull request by saj**
See the [original pull request here](https://github.com/olorin/nagiosplugin/pull/9).

Thoughts?

### CODE REVIEW

**Comment by cosmopetrich** [comment]
Works as expected. Vet/tests pass, and the tests look good.

The code looks good as far as this approach to the problem goes, though as you indicated in the upstream PR I do wonder about the complexity.

One of your comments in check.go described the issue well:

> A Nagios plugin must ultimately report a single status to its
> parent process (OK, CRITICAL, etc.). nagiosplugin allows plugin
> developers to batch multiple check results in a single plugin
> invocation. The most severe result will be reflected in the
> plugin's final exit status. By default, results are prioritised
> by the numeric 'plugin return codes' defined by the Nagios Plugin
> Development Guidelines. Results with CRITICAL status will take
> precedence over WARNING, WARNING over OK, and UNKNOWN over all
> other results.

The default behaviour makes sense to an extent. A WARNING is certainly of higher priority than an OK and lower than CRITICAL. I can't easily find the history of changes back in the early Nagios/Netsaint days, but I'd not be surprised the UNKNOWN state was added after the others and was arbitrarily assigned the next-highest exit code. Something like that could well be the origin of the convention to treat UNKNOWN as the highest priority state, rather than any intentional decision.

The argument you put forward for UNKNOWN being low priority in https://github.com/olorin/nagiosplugin/pull/8 is sound, but I can understand @olorin's reticence to make a change that both alters the current behaviour of the library and diverges from how many Nagios plugin libraries for other languages function.

U>C>W>O is the default, so we need to account for that. C>W>U>O is a possibly saner ordering, so it would be nice to be able to do that. Is it going to be a common requirement to want C>U>W>O, W>C>U>O, or something equally insane? It's good that this change can account for those edge cases, but I wonder if we save a fair bit of complexity (in implementation or usage) by disregarding them. YAGNI and all that.

I can't immediately offer any suggestions, I'll need to think a bit longer on it. Maybe it's a case of keeping this change as-is but offering a second predefined policy (though perhaps that's too specific). Maybe something like a boolean flag that toggles between the new and old behaviours in https://github.com/olorin/nagiosplugin/pull/8 (though that may be inelegant).

**Comment by cosmopetrich** [comment]
It might also be worth adding an example of whatever behaviour we settle on to README.md to highlight its availability.

For example:

```markdown
# Usage example

[...]

The final state of a check with multiple results is decided by comparing their [return codes](https://nagios-plugins.org/doc/guidelines.html#AEN78), with the highest code taking precedence. A status policy can be used to modify this behaviour, such as to have CRITICAL and WARNING to override UNKNOWN.

    <Insert your example test here>
```

**Comment by cosmopetrich** [comment]
> I can't easily find the history of changes back in the early Nagios/Netsaint days, but I'd not be surprised the UNKNOWN state was added after the others and was arbitrarily assigned the next-highest exit code. 

From https://nagios-plugins.org/doc/guidelines.html#AEN78

> The return codes below are based on the POSIX spec of returning a positive value. Netsaint prior to v0.0.7 supported non-POSIX compliant return code of "-1" for unknown. Nagios supports POSIX return codes by default.

**Comment by saj** [comment]
My [original PR to olorin's mainline](https://github.com/olorin/nagiosplugin/pull/9) was merged.  No need to fork (woo!) but I did not get a chance to incorporate your feedback.  I sent a [follow-up](https://github.com/olorin/nagiosplugin/pull/10) with your suggestions.

While I agree that the remaining orderings are unlikely to be used, I think the biggest jump in complexity was in the addition of the check knobs -- even with a flag, we cannot easily get around the need for something like `CheckOptions`.  The generic approach taken here also simplifies the comparisons made in `AddResult()`.

Closing.

**Pull request closed without merging**
